site_name: Pleiotropy Decomposition Pipeline
repo_url: https://github.com/gloriabenoit/PDP-Docs
site_author: Gloria BENOIT
site_description: Official documentation for our Pleiotropy Decomposition Pipeline.

nav:
    - About:
      - Overview: index.md
      - Implemented methods: methods.md
      - Repertory architecture: architecture.md
    - Set up:
      - Input data: input.md
      - Dependencies: dependencies.md
      - Parameters: parameters.md
    - Pipeline:
      - Preprocessing the data: preprocessing.md
      - Running the methods: running.md
      - Assembling the results: assembling.md

theme:
  name: readthedocs
  features:
    - content.code.copy

markdown_extensions:
  - admonition