site_name: Pleiotropy Decomposition Pipeline
repo_url: https://github.com/gloriabenoit/PDP-Docs
site_author: Gloria BENOIT
site_description: Official documentation for our Pleiotropy Decomposition Pipeline.

nav:
    - About:
      - Overview: index.md
      - Implemented methods: methods.md
    - Set up:
      - Input data: input.md
      - Dependencies: dependencies.md
    - Pipeline:
      - Parameters: parameters.md
      - Running the pipeline: running.md
      - Assembling the results: assembling.md

theme:
  name: readthedocs
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
